# Start with the golang v1.18 image
FROM golang:1.18.3-stretch

# Set a working directory
WORKDIR /app

# Copy the entire project
COPY . .

# Install all go_modules
RUN go mod tidy

# Specify the command from running tests
CMD go test -v ./test/...